rule.1.name=high-energy-premium-rule
rule.1.expression=#incident.type == T(com.znaji.domain.IncidentType).HOME_ENERGY_SPIKE && #incident.value > #incident.threshold && #incident.customerTier == T(com.znaji.domain.CustomerTier).PREMIUM
rule.1.plan=PREMIUM_ENERGY_ESCALATION

rule.2.name=normal-energy-rule
rule.2.expression=#incident.type == T(com.znaji.domain.IncidentType).HOME_ENERGY_SPIKE && #incident.value > #incident.threshold
rule.2.plan=NO_ACTION

rule.3.name=payment-failure-rule
rule.3.expression=#incident.type == T(com.znaji.domain.IncidentType).PAYMENT_FAILURE and (#incident.severity == T(com.znaji.domain.Severity).HIGH or #incident.severity == T(com.znaji.domain.Severity).CRITICAL)
rule.3.plan=PAYMENT_SUPPORT_ESCALATION